language: ruby
rvm:
  - 2.2.5

#before_script:
# - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script: jekyll build
# for html5proof ./script/cibuild && jekyll build && htmlproofer ./_site
